services:
  - type: web
    name: mern-crud-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: mongodb+srv://mern-crud-app:admin@sambait.s9lniuw.mongodb.net/?appName=SambaIT
      - key: CLIENT_URL
        sync: mern-crud-app-frontend-eight.vercel.app      
        #  http://localhost:5173      
